from __future__ import annotations

import hashlib
import random
from collections import defaultdict
from typing import Optional

from providers import ProviderError
from world_generation.agent_framework_compat import step
from world_generation.prompts.common import feedback_block, render_json_block
from world_generation.schemas import (
    AGE_BANDS,
    CHARACTER_CLUSTER_KINDS,
    NPC_COUNT,
    PRIMARY_RELATIONSHIP_TYPES,
    CharacterClusterDraft,
    CharacterDiagramStep,
    CharacterSegmentDraft,
    CharacterSlotDraft,
    FactionDraft,
    PlaceDraft,
    PlannedRelationshipDraft,
    RegionDraft,
    RelationshipOpportunityDraft,
)
from world_generation.step_runtime import AttemptRecord, StepTranscript, step_label, update_step


PRIMARY_COVERAGE_RATIO = 0.6
MAX_NPC_BATCH_SIZE = 4
STRUCTURAL_DESCRIPTION = "Structural heritage tie generated by the character diagram planner; NPC generation should make it specific."

PRIMARY_STRUCTURAL_TYPES = {
    "parent",
    "child",
    "sibling",
    "spouse",
    "betrothed",
    "former spouse",
    "guardian",
    "ward",
    "adoptive parent",
    "adoptive child",
    "household member",
    "chosen family",
}

SETTLED_PLACE_TYPES = {"town", "village", "fortress"}
SPARSE_PLACE_TYPES = {"dungeon", "ruin", "road", "landmark"}
AGE_RANK = {"child": 0, "teen": 1, "young adult": 2, "adult": 3, "elder": 4}


def character_diagram_shape() -> dict:
    return {
        "clusters": [
            {
                "ref": "cluster-household-kebab-case",
                "kind": "household",
                "place_ref": "place-kebab-case",
                "summary": "Short reason this character group matters.",
            }
        ],
        "slots": [
            {
                "ref": "npc-slot-kebab-case",
                "home_place_ref": "place-kebab-case",
                "current_place_ref": "place-kebab-case",
                "faction_ref": None,
                "age_band": "adult",
                "role_hint": "short character function before final NPC details",
                "cluster_ref": "cluster-household-kebab-case",
            }
        ],
        "relationships": [
            {
                "ref": "rel-plan-kebab-case",
                "source_ref": "npc-slot-kebab-case",
                "target_ref": "npc-slot-other-kebab-case",
                "relation_type": "parent",
                "description": STRUCTURAL_DESCRIPTION,
            }
        ],
    }


def build_messages(
    prompt: str,
    region: RegionDraft,
    places: list[PlaceDraft],
    factions: list[FactionDraft],
    previous_error: Optional[str] = None,
    previous_response: Optional[str] = None,
) -> list[dict[str, str]]:
    retry_feedback = feedback_block(previous_error, previous_response)
    prompt_body = f"""World prompt:
{prompt}

Region:
{render_json_block(region.model_dump())}

Places:
{render_json_block([place.model_dump() for place in places])}

Factions:
{render_json_block([faction.model_dump() for faction in factions])}

Task:
This step is now generated heuristically by the backend. If called, return JSON with clusters, slots, and primary structural relationships only.

Required JSON shape:
{render_json_block(character_diagram_shape())}
"""
    if retry_feedback:
        prompt_body += f"\nRetry feedback:\n{retry_feedback}\n"
    return [
        {"role": "system", "content": "You are the character relationship diagram specialist. Return one valid JSON object only."},
        {"role": "user", "content": prompt_body},
    ]


def _seed_for_world(prompt: str, region: RegionDraft, places: list[PlaceDraft], factions: list[FactionDraft]) -> int:
    seed_material = render_json_block(
        {
            "prompt": prompt,
            "region": region.model_dump(),
            "places": [place.model_dump() for place in places],
            "factions": [faction.model_dump() for faction in factions],
        }
    )
    return int(hashlib.sha256(seed_material.encode("utf-8")).hexdigest()[:16], 16)


def _slug(value: str) -> str:
    chars = []
    previous_dash = False
    for char in value.lower():
        if char.isalnum():
            chars.append(char)
            previous_dash = False
        elif not previous_dash:
            chars.append("-")
            previous_dash = True
    return "".join(chars).strip("-") or "node"


def _place_weight(place: PlaceDraft) -> int:
    weight = 2
    if place.place_type in SETTLED_PLACE_TYPES:
        weight += 8
    if place.place_type in SPARSE_PLACE_TYPES:
        weight -= 1
    if place.population_estimate > 0:
        weight += min(8, place.population_estimate // 250)
    if place.controlling_faction_ref:
        weight += 2
    weight += max(0, 4 - place.danger_level)
    return max(1, weight)


def _weighted_place_sequence(places: list[PlaceDraft], rng: random.Random) -> list[PlaceDraft]:
    weighted: list[PlaceDraft] = []
    for place in places:
        weighted.extend([place] * _place_weight(place))
    rng.shuffle(weighted)
    return weighted or places


def _nearby_places(place: PlaceDraft, places: list[PlaceDraft], *, limit: int = 4) -> list[PlaceDraft]:
    return sorted(
        [candidate for candidate in places if candidate.ref != place.ref],
        key=lambda candidate: (
            (candidate.x - place.x) ** 2 + (candidate.y - place.y) ** 2,
            candidate.ref,
        ),
    )[:limit]


def _controlled_faction(
    place: PlaceDraft,
    factions: list[FactionDraft],
    family_index: int,
    member_index: int,
    rng: random.Random,
) -> Optional[str]:
    if not factions:
        return None
    base_ref = place.controlling_faction_ref
    if base_ref is None and (family_index + member_index) % 3 == 0:
        base_ref = factions[(family_index + member_index) % len(factions)].ref
    if (family_index + member_index) % 11 == 0:
        alternatives = [faction.ref for faction in factions if faction.ref != base_ref]
        if alternatives:
            return rng.choice(alternatives)
    return base_ref


def _current_place(
    home_place: PlaceDraft,
    places: list[PlaceDraft],
    family_index: int,
    member_index: int,
    rng: random.Random,
) -> PlaceDraft:
    if (family_index + member_index) % 7 != 0:
        return home_place
    nearby = _nearby_places(home_place, places)
    return rng.choice(nearby) if nearby else home_place


def _family_age_bands(size: int, family_index: int) -> list[str]:
    templates = {
        2: [["adult", "adult"], ["elder", "adult"], ["young adult", "teen"]],
        3: [["adult", "adult", "child"], ["adult", "young adult", "teen"], ["elder", "adult", "young adult"]],
        4: [["adult", "adult", "teen", "child"], ["elder", "adult", "adult", "young adult"], ["adult", "adult", "young adult", "teen"]],
        5: [["elder", "adult", "adult", "teen", "child"], ["adult", "adult", "young adult", "teen", "child"]],
        6: [["elder", "adult", "adult", "young adult", "teen", "child"]],
    }
    choices = templates.get(size, templates[4])
    return choices[family_index % len(choices)]


def _role_hint(age_band: str, family_index: int, member_index: int, place: PlaceDraft, faction_ref: Optional[str]) -> str:
    if member_index == 0 and age_band in {"adult", "elder"}:
        return f"family anchor tied to {place.name}"
    if faction_ref:
        return "family member with faction obligations"
    if age_band in {"child", "teen"}:
        return "younger family member shaped by household pressures"
    if age_band == "elder":
        return "elder relative who remembers older family history"
    return "working family member with local responsibilities"


def _relationship(
    ref: str,
    source_ref: str,
    target_ref: str,
    relation_type: str,
) -> PlannedRelationshipDraft:
    return PlannedRelationshipDraft(
        ref=ref,
        source_ref=source_ref,
        target_ref=target_ref,
        relation_type=relation_type,
        description=STRUCTURAL_DESCRIPTION,
    )


def _add_family_relationships(
    relationships: list[PlannedRelationshipDraft],
    family_slots: list[CharacterSlotDraft],
    family_index: int,
) -> None:
    adults = [slot for slot in family_slots if slot.age_band in {"young adult", "adult", "elder"}]
    children = [slot for slot in family_slots if slot.age_band in {"child", "teen", "young adult"}]
    parents = [slot for slot in family_slots if slot.age_band in {"adult", "elder"}][:2]

    if len(adults) >= 2:
        relation_type = "spouse" if family_index % 4 else "former spouse"
        relationships.append(_relationship(f"rel-plan-{relation_type.replace(' ', '-')}-{family_index:03d}", adults[0].ref, adults[1].ref, relation_type))

    for child in children:
        for parent_index, parent in enumerate(parents):
            if parent.ref == child.ref or AGE_RANK[parent.age_band] < AGE_RANK[child.age_band]:
                continue
            relationships.append(_relationship(f"rel-plan-parent-{family_index:03d}-{parent_index + 1}-{child.ref[-2:]}", parent.ref, child.ref, "parent"))

    young = [slot for slot in family_slots if slot.age_band in {"child", "teen", "young adult"}]
    for idx in range(len(young) - 1):
        relationships.append(_relationship(f"rel-plan-sibling-{family_index:03d}-{idx + 1}", young[idx].ref, young[idx + 1].ref, "sibling"))

    connected = {rel.source_ref for rel in relationships}.union({rel.target_ref for rel in relationships})
    anchor = family_slots[0]
    for slot in family_slots:
        if slot.ref not in connected and slot.ref != anchor.ref:
            relationships.append(_relationship(f"rel-plan-household-{family_index:03d}-{slot.ref[-2:]}", anchor.ref, slot.ref, "household member"))


def _family_sizes(rng: random.Random) -> list[int]:
    sizes: list[int] = []
    total = 0
    pattern = [5, 4, 3, 6, 4, 2, 5, 3]
    while total < NPC_COUNT:
        size = pattern[len(sizes) % len(pattern)]
        size += rng.choice([-1, 0, 0, 1])
        size = max(2, min(6, size))
        if NPC_COUNT - total - size == 1:
            size += 1
        if total + size > NPC_COUNT:
            size = NPC_COUNT - total
        if size == 1 and sizes:
            sizes[-1] += 1
            break
        sizes.append(size)
        total += size
    return sizes


def _add_marriage_bridges(
    relationships: list[PlannedRelationshipDraft],
    slots_by_cluster: dict[str, list[CharacterSlotDraft]],
    rng: random.Random,
) -> list[RelationshipOpportunityDraft]:
    opportunities: list[RelationshipOpportunityDraft] = []
    cluster_refs = sorted(slots_by_cluster)
    for idx in range(0, len(cluster_refs) - 1, 2):
        source_options = [slot for slot in slots_by_cluster[cluster_refs[idx]] if slot.age_band in {"young adult", "adult"}]
        target_options = [slot for slot in slots_by_cluster[cluster_refs[idx + 1]] if slot.age_band in {"young adult", "adult"}]
        if not source_options or not target_options:
            continue
        source = rng.choice(source_options)
        target = rng.choice(target_options)
        relation_type = "spouse" if idx % 4 else "betrothed"
        relationships.append(_relationship(f"rel-plan-marriage-bridge-{idx // 2 + 1:03d}", source.ref, target.ref, relation_type))
        opportunities.append(
            RelationshipOpportunityDraft(
                ref=f"opp-marriage-bridge-{idx // 2 + 1:03d}",
                kind="marriage_bridge",
                slot_refs=[source.ref, target.ref],
                summary="Two family clusters are structurally connected by a marriage or betrothal; let later AI decide the social consequences.",
            )
        )
    return opportunities


def _build_segments(
    clusters: list[CharacterClusterDraft],
    slots_by_cluster: dict[str, list[CharacterSlotDraft]],
) -> list[CharacterSegmentDraft]:
    segments: list[CharacterSegmentDraft] = []
    pending: list[str] = []
    pending_slots: list[str] = []
    for cluster in clusters:
        cluster_slots = [slot.ref for slot in slots_by_cluster[cluster.ref]]
        if pending and len(pending_slots) + len(cluster_slots) > MAX_NPC_BATCH_SIZE:
            segment_ref = f"segment-family-{len(segments) + 1:03d}"
            segments.append(
                CharacterSegmentDraft(
                    ref=segment_ref,
                    cluster_refs=pending,
                    slot_refs=pending_slots,
                    summary="Graph-aware family generation segment.",
                )
            )
            pending = []
            pending_slots = []
        pending.append(cluster.ref)
        pending_slots.extend(cluster_slots)
    if pending:
        segment_ref = f"segment-family-{len(segments) + 1:03d}"
        segments.append(
            CharacterSegmentDraft(
                ref=segment_ref,
                cluster_refs=pending,
                slot_refs=pending_slots,
                summary="Graph-aware family generation segment.",
            )
        )
    return segments


def build_character_diagram(
    prompt: str,
    region: RegionDraft,
    places: list[PlaceDraft],
    factions: list[FactionDraft],
) -> tuple[CharacterDiagramStep, list[RelationshipOpportunityDraft], list[CharacterSegmentDraft]]:
    if not places:
        raise ProviderError("Places must exist before character diagram generation.")

    rng = random.Random(_seed_for_world(prompt, region, places, factions))
    place_sequence = _weighted_place_sequence(places, rng)
    family_sizes = _family_sizes(rng)

    clusters: list[CharacterClusterDraft] = []
    slots: list[CharacterSlotDraft] = []
    relationships: list[PlannedRelationshipDraft] = []
    opportunities: list[RelationshipOpportunityDraft] = []
    slots_by_cluster: dict[str, list[CharacterSlotDraft]] = {}

    slot_index = 1
    for family_index, family_size in enumerate(family_sizes, start=1):
        place = place_sequence[(family_index - 1) % len(place_sequence)]
        cluster_ref = f"cluster-family-{family_index:03d}-{_slug(place.ref)}"
        cluster = CharacterClusterDraft(
            ref=cluster_ref,
            kind="family" if family_index % 5 else "household",
            place_ref=place.ref,
            summary="Structural family or household cluster generated before NPC details.",
        )
        clusters.append(cluster)

        family_slots: list[CharacterSlotDraft] = []
        age_bands = _family_age_bands(family_size, family_index)
        for member_index, age_band in enumerate(age_bands, start=1):
            current = _current_place(place, places, family_index, member_index, rng)
            faction_ref = _controlled_faction(place, factions, family_index, member_index, rng)
            slot = CharacterSlotDraft(
                ref=f"npc-slot-{slot_index:03d}",
                home_place_ref=place.ref,
                current_place_ref=current.ref,
                faction_ref=faction_ref,
                age_band=age_band,
                role_hint=_role_hint(age_band, family_index, member_index, place, faction_ref),
                cluster_ref=cluster_ref,
            )
            slots.append(slot)
            family_slots.append(slot)
            if current.ref != place.ref:
                opportunities.append(
                    RelationshipOpportunityDraft(
                        ref=f"opp-moved-away-{slot_index:03d}",
                        kind="moved_away",
                        slot_refs=[slot.ref],
                        place_refs=[place.ref, current.ref],
                        summary="This slot currently lives away from their family home; later AI may decide whether that creates tension, duty, exile, work, or opportunity.",
                    )
                )
            if faction_ref and place.controlling_faction_ref and faction_ref != place.controlling_faction_ref:
                opportunities.append(
                    RelationshipOpportunityDraft(
                        ref=f"opp-faction-mismatch-{slot_index:03d}",
                        kind="faction_mismatch",
                        slot_refs=[slot.ref],
                        place_refs=[place.ref],
                        faction_refs=[place.controlling_faction_ref, faction_ref],
                        summary="This slot's faction differs from their home place's controlling faction; later AI may decide what that means.",
                    )
                )
            slot_index += 1

        slots_by_cluster[cluster_ref] = family_slots
        _add_family_relationships(relationships, family_slots, family_index)

    opportunities.extend(_add_marriage_bridges(relationships, slots_by_cluster, rng))
    for faction in factions:
        faction_slots = [slot.ref for slot in slots if slot.faction_ref == faction.ref][:6]
        if len(faction_slots) >= 2:
            opportunities.append(
                RelationshipOpportunityDraft(
                    ref=f"opp-same-faction-{_slug(faction.ref)}",
                    kind="same_faction",
                    slot_refs=faction_slots,
                    faction_refs=[faction.ref],
                    summary="Several slots share faction membership; final relationships may turn this into loyalty, rivalry, mentorship, debt, secrecy, or command structure.",
                )
            )

    segments = _build_segments(clusters, slots_by_cluster)
    diagram = CharacterDiagramStep(clusters=clusters, slots=slots, relationships=relationships)
    validate_character_diagram(diagram, places, factions)
    return diagram, opportunities, segments


def _validate_family_age_band(relationship_type: str, source_band: str, target_band: str, relationship_ref: str) -> None:
    if relationship_type in {"parent", "guardian", "adoptive parent"}:
        if source_band not in {"adult", "elder"} or AGE_RANK[source_band] < AGE_RANK[target_band]:
            raise ValueError(f"Planned relationship {relationship_ref} has implausible {relationship_type} age bands.")
    if relationship_type in {"child", "ward", "adoptive child"}:
        if target_band not in {"adult", "elder"} or AGE_RANK[source_band] > AGE_RANK[target_band]:
            raise ValueError(f"Planned relationship {relationship_ref} has implausible {relationship_type} age bands.")


def validate_character_diagram(parsed: CharacterDiagramStep, places: list[PlaceDraft], factions: list[FactionDraft]) -> None:
    place_refs = {place.ref for place in places}
    faction_refs = {faction.ref for faction in factions}
    cluster_refs = [cluster.ref for cluster in parsed.clusters]
    slot_refs = [slot.ref for slot in parsed.slots]

    if len(cluster_refs) != len(set(cluster_refs)):
        raise ValueError("Character diagram produced duplicate cluster refs.")
    if len(slot_refs) != NPC_COUNT:
        raise ValueError(f"Character diagram produced {len(slot_refs)} slots instead of {NPC_COUNT}.")
    if len(slot_refs) != len(set(slot_refs)):
        raise ValueError("Character diagram produced duplicate slot refs.")

    cluster_ref_set = set(cluster_refs)
    for cluster in parsed.clusters:
        if cluster.place_ref not in place_refs:
            raise ValueError(f"Character cluster {cluster.ref} references unknown place {cluster.place_ref}.")
        if cluster.kind not in CHARACTER_CLUSTER_KINDS:
            raise ValueError(f"Character cluster {cluster.ref} uses invalid kind {cluster.kind}.")

    slots_by_ref = {slot.ref: slot for slot in parsed.slots}
    for slot in parsed.slots:
        if slot.home_place_ref not in place_refs:
            raise ValueError(f"Character slot {slot.ref} references unknown home place {slot.home_place_ref}.")
        if slot.current_place_ref not in place_refs:
            raise ValueError(f"Character slot {slot.ref} references unknown current place {slot.current_place_ref}.")
        if slot.faction_ref and slot.faction_ref not in faction_refs:
            raise ValueError(f"Character slot {slot.ref} references unknown faction {slot.faction_ref}.")
        if slot.cluster_ref not in cluster_ref_set:
            raise ValueError(f"Character slot {slot.ref} references unknown cluster {slot.cluster_ref}.")
        if slot.age_band not in AGE_BANDS:
            raise ValueError(f"Character slot {slot.ref} uses invalid age band {slot.age_band}.")

    seen_relationship_refs: set[str] = set()
    connected_slots: set[str] = set()
    primary_connected_slots: set[str] = set()
    for relationship in parsed.relationships:
        if relationship.ref in seen_relationship_refs:
            raise ValueError(f"Character diagram produced duplicate relationship ref {relationship.ref}.")
        seen_relationship_refs.add(relationship.ref)
        if relationship.source_ref == relationship.target_ref:
            raise ValueError(f"Planned relationship {relationship.ref} cannot target the same slot.")
        if relationship.source_ref not in slots_by_ref:
            raise ValueError(f"Planned relationship {relationship.ref} references unknown source slot {relationship.source_ref}.")
        if relationship.target_ref not in slots_by_ref:
            raise ValueError(f"Planned relationship {relationship.ref} references unknown target slot {relationship.target_ref}.")
        if relationship.relation_type not in PRIMARY_STRUCTURAL_TYPES:
            raise ValueError(f"Planned relationship {relationship.ref} must be a primary structural type; got {relationship.relation_type}.")
        connected_slots.update({relationship.source_ref, relationship.target_ref})
        if relationship.relation_type in PRIMARY_RELATIONSHIP_TYPES:
            primary_connected_slots.update({relationship.source_ref, relationship.target_ref})
        source = slots_by_ref[relationship.source_ref]
        target = slots_by_ref[relationship.target_ref]
        _validate_family_age_band(relationship.relation_type, source.age_band, target.age_band, relationship.ref)

    missing_connections = sorted(set(slot_refs) - connected_slots)
    if missing_connections:
        raise ValueError(f"Every character slot must have at least one planned relationship. Missing: {missing_connections}.")

    required_primary_count = int(NPC_COUNT * PRIMARY_COVERAGE_RATIO)
    if len(primary_connected_slots) < required_primary_count:
        raise ValueError(
            f"Primary relationships must cover at least {required_primary_count} slots; got {len(primary_connected_slots)}."
        )


@step(name="character_diagram")
async def run_step(state):
    if state.region_step is None or state.places_step is None or state.factions_step is None:
        raise ProviderError("Region, places, and factions steps must complete before character diagram generation.")

    await update_step(state.updater, "character_diagram", "running", attempts=1, error="")
    diagram, opportunities, segments = build_character_diagram(
        state.prompt,
        state.region_step.region,
        state.places_step.places,
        state.factions_step.factions,
    )
    parsed_payload = {
        **diagram.model_dump(),
        "relationship_opportunities": [opportunity.model_dump() for opportunity in opportunities],
        "character_segments": [segment.model_dump() for segment in segments],
    }
    transcript = StepTranscript(
        name="character_diagram",
        label=step_label("character_diagram"),
        status="done",
        attempts=[
            AttemptRecord(
                attempt=1,
                status="done",
                raw_response=render_json_block(parsed_payload),
                latency_ms=0,
                parsed_payload=parsed_payload,
            )
        ],
        latency_ms=0,
        parsed_payload=parsed_payload,
    )
    state.step_transcripts.append(transcript)
    state.character_diagram_step = diagram
    state.relationship_opportunities = opportunities
    state.character_segments = segments
    await update_step(
        state.updater,
        "character_diagram",
        "done",
        attempts=1,
        error="",
        raw_response=render_json_block(parsed_payload),
        parsed_payload=parsed_payload,
        latency_ms=0,
    )
    return state
